!!com.lingxicloud.uis.manage.core.domain.zuul.Zuul
zuul:
  routes:
    application-demo: {path: /application-demo/**, sensitiveHeaders: '', serviceId: APPLICATION-DEMO,
      stripPrefix: true}
    api-gateway: {path: /api-gateway/**, sensitiveHeaders: '', serviceId: API-GATEWAY,
      stripPrefix: true}
