server:
  port: 8765
spring:
  application:
    name: eurekaclient

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh

spring:
  rabbitmq:                     #本地环境不需要配置mq
      host: 192.168.109.138
      port: 5672
      username: guest
      password: guest
 